src/main/java/br/com/softplan/moduloI/model/Cargo.java
package br.com.softplan.moduloI.model;

import java.io.Serializable;

public class Cargo implements Serializable {
	private static final long serialVersionUID = 1L;

	private Long id;
	private String descricao;

	public Cargo() {
		super();
	}
	
	public Cargo(String descricao) {
		this();
		this.descricao = descricao;
	}
	
	public Cargo(Long id, String descricao) {
		this(descricao);
		this.id = id;
	}
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cargo other = (Cargo) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Cargo [id=" + id + ", descricao=" + descricao + "]";
	}

}

src/main/java/br/com/softplan/moduloI/model/Categoria.java
package br.com.softplan.moduloI.model;

import java.io.Serializable;

public class Categoria implements Serializable {
	private static final long serialVersionUID = 1L;

	private Long id;
	private String descricao;

	public Categoria() {
		super();
	}

	public Categoria(String descricao) {
		this();
		this.descricao = descricao;
	}

	public Categoria(Long id, String descricao) {
		this(descricao);
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Categoria other = (Categoria) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Categoria [id=" + id + ", descricao=" + descricao + "]";
	}

}

src/main/java/br/com/softplan/moduloI/controller/CategoriaMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;

import br.com.softplan.moduloI.dao.CategoriaDAO;
import br.com.softplan.moduloII.model.Categoria;
import br.com.softplan.moduloIII.interceptors.Logger;
import br.com.softplan.moduloIII.stereotypes.Controller;

@Controller
@ConversationScoped
public class CategoriaMB implements Serializable {
	private static final long serialVersionUID = 1L;

	private Categoria categoria = new Categoria();
	private DataModel<Categoria> categorias;

	@Inject
	private CategoriaDAO categoriaDAO;

	@Inject
	private Conversation conversation;

	public DataModel<Categoria> getCategorias() {
		if (this.categorias == null) {
			List<Categoria> lista = categoriaDAO.loadAll();
			categorias = new ListDataModel<>(lista);

		}
		return categorias;
	}

	@Logger
	public void salvar() {
		System.out.println("Execuntando o salvar...");
		FacesContext ctx = FacesContext.getCurrentInstance();
		try {
			categoriaDAO.save(this.categoria);
			this.categoria = new Categoria();
			ctx.addMessage(null, new FacesMessage("Categoria salva com sucesso!"));

			if (!conversation.isTransient())
				conversation.end();

			this.categoria = null;

		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao salvar categoria", e.getMessage()));
		}
	}

	public String novo() {
		if (conversation.isTransient())
			conversation.begin();

		this.categoria = new Categoria();
		return "/moduloI/categoria/cadastrar";
	}

	public String editar() {
		if (!conversation.isTransient())
			conversation.begin();

		this.categoria = categorias.getRowData();
		return "/moduloI/categoria/cadastrar";
	}

	public void excluir() {
		FacesContext ctx = FacesContext.getCurrentInstance();
		try {
			categoriaDAO.remover(categorias.getRowData());
			ctx.addMessage(null, new FacesMessage("Categoria removida com sucesso."));

			if (!conversation.isTransient())
				conversation.end();

			this.categorias = null;
		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao remover um categoria ", e.getMessage()));

		}

	}

	public void valueAlterado(ValueChangeEvent evento) {
		System.out.println("Processando o evento de mudança de valor em [valueAlterado]");
		System.out.println("Valor antes: " + evento.getOldValue());
		System.out.println("Valor depois: " + evento.getNewValue());
	}

	public void botaoPressionado(ActionEvent evento) {
		System.out.println("Processando o evento de ação em [botaoPressionado]");
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}
}

src/main/java/br/com/softplan/moduloI/controller/ComponenteMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;

import javax.faces.model.SelectItem;

import br.com.softplan.moduloIII.stereotypes.Controller;

/*@ManagedBean
@Named*/
@Controller
public class ComponenteMB implements Serializable {
	private static final long serialVersionUID = 2375864423040475581L;

	private String sexoSelecionado;
	private boolean receberEmail;
	private ArrayList<String> generosSelecionados;

	
	public void executar() {
		System.out.println("Sexo: " + sexoSelecionado + "\n" +
				"Receber email: " + (receberEmail ? "SIM" : "NÂO") +
				"\n" + "Generos: " + generosSelecionados);
	}

	
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public Collection getGeneros() {
		Collection generos = new ArrayList();
		generos.add(new SelectItem("Ficcao", "Ficção"));
		generos.add(new SelectItem("Biografia", "Biografia"));
		generos.add(new SelectItem("NaoFiccao", "Não Ficção"));
		
		return generos;
	}
	public ArrayList<String> getGenerosSelecionados() {
		return generosSelecionados;
	}
	
	public void setGenerosSelecionados(ArrayList<String> generosSelecionados) {
		this.generosSelecionados = generosSelecionados;
	}

	public boolean isReceberEmail() {
		return receberEmail;
	}

	public void setReceberEmail(boolean receberEmail) {
		this.receberEmail = receberEmail;
	}

	public String getSexoSelecionado() {
		return sexoSelecionado;
	}

	public void setSexoSelecionado(String sexoSelecionado) {
		this.sexoSelecionado = sexoSelecionado;
	}

}

src/main/java/br/com/softplan/moduloI/controller/Controller.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.ManagedBean;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

import br.com.softplan.moduloII.model.Categoria;


@ManagedBean
@Named
@SessionScoped
public class Controller implements Serializable {
	private static final long serialVersionUID = -756779740745040007L;

	private String categoria;

	@PersistenceContext
	private EntityManager em;

	public Controller() {
		System.out.println("Instânciando o [Controller]");
	}

	public void metodo() {
		System.out.println("[Controller] Executando o método.");
		System.out.println("[Controller] Entity<Manager: " + em);
		Categoria categoria = em.find(Categoria.class, 34L);
		System.out.println("Categoria: " + categoria.getDescricao());
		this.categoria = categoria.getDescricao();
		TypedQuery<Categoria> query = em.createQuery("select c from Categoria c", Categoria.class);
		List<Categoria> lista = query.getResultList();
		System.out.println(lista.size());
	}

	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
}

src/main/java/br/com/softplan/moduloI/controller/ExemploMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;

import br.com.softplan.moduloIII.stereotypes.Controller;


/*@ManagedBean
@Named*/
@Controller
public class ExemploMB implements Serializable{
	private static final long serialVersionUID = -2710964415287298930L;
	
	private String nome;
	
	public ExemploMB() {
		System.out.println("Criando uma instância de ExemploMB");
	}
	
	public void exeutar() {
		System.out.println("Executando o método ....");
		System.out.println("Nome: " + nome);
	}

	public String getNome() {
		System.out.println("Obtendo o nome: " + nome);
		return nome;
	}
	
	public void setNome(String nome) {
		System.out.println("Alterando o nome: " + nome);
		this.nome = nome;
	}
}

src/main/java/br/com/softplan/moduloI/controller/FuncionarioMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

import br.com.softplan.moduloI.dao.CargoDAO;
import br.com.softplan.moduloI.dao.FuncionarioDAO;
import br.com.softplan.moduloI.model.Cargo;
import br.com.softplan.moduloI.model.Funcionario;
import br.com.softplan.moduloIII.stereotypes.Controller;

/*@ManagedBean
@Named*/
@Controller
@SessionScoped
public class FuncionarioMB implements Serializable {
	private static final long serialVersionUID = 1L;

	private Funcionario funcionario = new Funcionario();
	private DataModel<Funcionario> funcionarios;

	public DataModel<Funcionario> getFuncionarios() {
		List<Funcionario> lista = FuncionarioDAO.getInstance().loadAll();
		funcionarios = new ListDataModel<Funcionario>(lista);
		return funcionarios;
	}

	public Collection<SelectItem> getCargosItens() {
		List<Cargo> cargos = CargoDAO.getInstance().loadAll();
		Collection<SelectItem> itens = new ArrayList<SelectItem>();
		for (Cargo c : cargos) {
			itens.add(new SelectItem(c, c.getDescricao()));
		}
		return itens;
	}

	public void salvar() {
		System.out.println("Salvando funcionário ...");
		FacesContext ctx = FacesContext.getCurrentInstance();
		try {
			FuncionarioDAO.getInstance().save(funcionario);
			ctx.addMessage(null, new FacesMessage("Funcinário salvo com sucesso!"));
			this.funcionario = new Funcionario();

		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao salvar funcionário", e.getMessage()));
		}
	}

	public String novo() {
		funcionario = new Funcionario();
		return "cadastrar";
	}

	public String editar() {
		this.funcionario = funcionarios.getRowData();
		return "editar";
	}

	public void remover() {
		System.out.println("Removendo funcionário");
		FacesContext ctx = FacesContext.getCurrentInstance();
		try {
			Funcionario f = funcionarios.getRowData();
			FuncionarioDAO.getInstance().remover(f);
			ctx.addMessage(null, new FacesMessage("Funcionário removido com sucesso!"));
		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro ao remover funcionário", e.getMessage()));
		}
	}

	public Funcionario getFuncionario() {
		return funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}
}

src/main/java/br/com/softplan/moduloI/controller/LoginMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;

import br.com.softplan.moduloIII.stereotypes.Controller;

/*@ManagedBean
@Named*/
@Controller
public class LoginMB implements Serializable{
	private static final long serialVersionUID = -8787444599758209194L;
	
	
	private String login;
	private String senha;
	
	public LoginMB() {
		
	}
	
	public void autenticar() {
		System.out.println("Loging: " + login +"\n"
				+ "Senha: " + senha);
	}
	
	
	public String getLogin() {
		return login;
	}
	
	public void setLogin(String login) {
		this.login = login;
	}
	
	public String getSenha() {
		return senha;
	}
	
	public void setSenha(String senha) {
		this.senha = senha;
	}

}

src/main/java/br/com/softplan/moduloI/controller/ProdutoMB.java
package br.com.softplan.moduloI.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;

import br.com.softplan.moduloI.dao.CategoriaDAO;
import br.com.softplan.moduloI.dao.ProdutoDAO;
import br.com.softplan.moduloII.model.Categoria;
import br.com.softplan.moduloII.model.Produto;
import br.com.softplan.moduloIII.stereotypes.Controller;

@Controller
@SessionScoped
public class ProdutoMB implements Serializable {
	private static final long serialVersionUID = 7047490450282580036L;

	@Inject
	private ProdutoDAO produtoDAO;

	@Inject
	private CategoriaDAO categoriaDAO;

	private DataModel<Produto> produtos;
	private Produto prosutoSelecionado;

	public ProdutoMB() {
		super();
		System.out.println("Criando instância de [ProdutoMB]");
		this.prosutoSelecionado = new Produto();
	}

	public DataModel<Produto> getProdutos() {
		if (this.produtos == null) {
			List<Produto> lista = produtoDAO.loadAll();
			produtos = new ListDataModel<>(lista);

		}
		return produtos;
	}

	public Collection<SelectItem> getCategorias() {
		List<Categoria> lista = categoriaDAO.loadAll();
		Collection<SelectItem> itens = new ArrayList<SelectItem>();
		for (Categoria categoria : lista) {
			itens.add(new SelectItem(categoria, categoria.getDescricao()));
		}

		return itens;
	}

	public void salvar() {
		FacesContext ctx = FacesContext.getCurrentInstance();

		try {
			produtoDAO.save(prosutoSelecionado);
			prosutoSelecionado = new Produto();
			ctx.addMessage(null, new FacesMessage("Produto salvo com sucesso"));
		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocorreu um erro ao salvar o produto", "Erro"));
		}
	}

	public String editar() {
		this.prosutoSelecionado = produtos.getRowData();
		return "/moduloI/produto/cadastrar";
	}

	public String novo() {
		return "/moduloI/produto/cadastrar";
	}

	public void excluir() {
		FacesContext ctx = FacesContext.getCurrentInstance();
		try {
			produtoDAO.remove(produtos.getRowData());
			ctx.addMessage(null, new FacesMessage("Produto excluido com sucesso"));
			this.produtos = null;
		} catch (Exception e) {
			ctx.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ocorreu um erro ao excluir um produto", "Erro"));
		}
	}

	public void tradatorEvento(AjaxBehaviorEvent event) {
		System.out.println("Executando o método [tradatorEvento]");
		UIInput input = (UIInput) event.getComponent();
		Categoria categoria = (Categoria) input.getValue();
		prosutoSelecionado.setDescricao(categoria.getDescricao());

		if (categoria.getDescricao().equalsIgnoreCase("DVD")) {
			prosutoSelecionado.setPreco(150.50);
		} else {
			prosutoSelecionado.setPreco(0.00);
		}

	}

	public Produto getProdutoSelecionado() {
		return prosutoSelecionado;
	}

	public void setProdutoSelecionado(Produto produtoSelecionaodo) {
		this.prosutoSelecionado = produtoSelecionaodo;
	}

	public void setProdutos(DataModel<Produto> produtos) {
		this.produtos = produtos;
	}
}

src/main/webapp/moduloI/funcionario/cadastrar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Soft Plan JEE</title>
</h:head>

<h:body>
	<h1>Cadastro Funcionário</h1>
	<h:form>
		<h:messages />

		<h:panelGrid columns="2">
			<f:facet name="header">
				<h:outputText value="Dados do Funcionário" />
			</f:facet>

			<h:outputLabel value="Nome: " for="itNome" />
			<h:inputText value="#{funcionarioMB.funcionario.nome}" id="itNome" required="true"/>

			<h:outputLabel value="Telefone: " for="itTelefone" />
			<h:inputText value="#{funcionarioMB.funcionario.telefone}"
				id="itTelefone" />

			<h:outputLabel value="Data Admissão: " for="itData" />
			<h:inputText value="#{funcionarioMB.funcionario.dataAdmissao}"
				id="itData" />

			<h:outputLabel value="Salário: " for="itSalario" />
			<h:inputText value="#{funcionarioMB.funcionario.salario}"
				id="itSalario" />

			<h:outputLabel value="Sexo: " for="itSexo" />
			<h:selectOneRadio value="#{funcionarioMB.funcionario.sexo}" id="itSexo">
				<f:selectItem itemValue="M" itemLabel="Masculino" />
				<f:selectItem itemValue="F" itemLabel="Femenino" />
			</h:selectOneRadio>

			<h:outputLabel value="Cargo: " for="itCargo" />
			<h:selectOneMenu value="#{funcionarioMB.funcionario.cargo}"
				id="itCargo">
				<f:converter converterId="meuConversorCargo" />
				<f:selectItems value="#{funcionarioMB.cargosItens}"  />
			</h:selectOneMenu>
			
			<f:facet name="footer">
				<h:commandButton action="#{funcionarioMB.salvar()}" value="Salvar" />
				<h:commandButton action="#{funcionarioMB.novo()}" value="Novo" />
			</f:facet>
		</h:panelGrid>
	<br/>
	<h:link outcome="/moduloI/navegation.jsf" value="Voltar" />
	</h:form>
	
</h:body>
</html>

src/main/webapp/moduloI/funcionario/editar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Soft Plan JEE</title>
</h:head>

<h:body>
	<h1>Atualizar Funcionário</h1>
	<h:form>
		<h:messages />

		<h:panelGrid columns="2">
			<f:facet name="header">
				<h:outputText value="Dados do Funcionário" />
			</f:facet>

			<h:outputLabel value="Nome: " for="itNome" />
			<h:inputText value="#{funcionarioMB.funcionario.nome}" id="itNome" />

			<h:outputLabel value="Telefone: " for="itTelefone" />
			<h:inputText value="#{funcionarioMB.funcionario.telefone}"
				id="itTelefone" />

			<h:outputLabel value="Data Admissão: " for="itData" />
			<h:inputText value="#{funcionarioMB.funcionario.dataAdmissao}"
				id="itData" />

			<h:outputLabel value="Salário: " for="itSalario" />
			<h:inputText value="#{funcionarioMB.funcionario.salario}"
				id="itSalario" />

			<h:outputLabel value="Sexo: " for="itSexo" />
			<h:selectOneRadio value="#{funcionarioMB.funcionario.sexo}">
				<f:selectItem itemValue="M" itemLabel="Masculino" />
				<f:selectItem itemValue="F" itemLabel="Femenino" />
			</h:selectOneRadio>

			<h:outputLabel value="Cargo: " for="itCargo" />
			<h:selectOneMenu value="#{funcionarioMB.funcionario.cargo}"
				id="itCargo">
				<f:converter converterId="meuConversorCargo"/>
				<f:selectItems value="#{funcionarioMB.cargosItens}"  />
			</h:selectOneMenu>
			
			<f:facet name="footer">
				<h:commandButton action="#{funcionarioMB.salvar()}" value="Salvar" />
				<h:commandButton action="#{funcionarioMB.novo()}" value="Novo" />
			</f:facet>
		</h:panelGrid>
	<br/>
	<h:commandLink action="/moduloI/navegation.jsf" value="Voltar" />
	</h:form>
	
</h:body>
</html>

src/main/webapp/moduloI/funcionario/listar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Softplan JEE</title>
</h:head>
<h:body>
	<h1>Lista de Funcionários</h1>
</h:body>
<h:form>
	<h:messages />
	<h:dataTable value="#{funcionarioMB.funcionarios}" var="funcionario" border="1">
		<f:facet name="header">
			<h:outputText value="Funcinários" />
		</f:facet>
		<h:column>
			<f:facet name="header">
				<h:outputText value="ID" />
			</f:facet>
			<h:outputText value="#{funcionario.id}" />
		</h:column>

		<h:column>
			<f:facet name="header">
				<h:outputText value="Nome" />
			</f:facet>
			<h:outputText value="#{funcionario.nome}" />
		</h:column>
		
		<h:column>
			<f:facet name="header">
				<h:outputText value="Telefone" />
			</f:facet>
			<h:outputText value="#{funcionario.telefone}" />
		</h:column>
		
		<h:column>
			<f:facet name="header">
				<h:outputText value="Dt. Adminssão" />
			</f:facet>
			<h:outputText value="#{funcionario.telefone}" />
		</h:column>
		
		<h:column>
			<f:facet name="header">
				<h:outputText value="Cargo" />
			</f:facet>
			<h:outputText value="#{funcionario.cargo.descricao}" >
			</h:outputText>
		</h:column>

		<h:column>
			<f:facet name="header">
				<h:outputText value="Salário" />
			</f:facet>
			<h:outputText value="#{funcionario.salario}" />
		</h:column>
		
		<h:column>
			<f:facet name="header">
				<h:outputText value="Ações" />
			</f:facet>
			<h:commandButton action="#{funcionarioMB.editar()}" value="Editar" />
			<h:commandButton action="#{funcionarioMB.remover()}" value="Excluir" />
		</h:column>
		<br/>
	</h:dataTable>
		<h:commandLink action="/moduloI/navegation.jsf" value="Voltar à tela inicial" />
</h:form>
</html>