src/main/java/br/com/softplan/moduloIII/model/ContaBancaria.java
package br.com.softplan.moduloIII.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.com.softplan.moduloIII.enums.Banco;
import br.com.softplan.moduloIII.exception.SaldoInsuficienteException;

@Entity
@Table(name = "contas", schema = "softplan")
public class ContaBancaria implements Serializable {
	private static final long serialVersionUID = -370706484571498619L;

	@Id
	@SequenceGenerator(name = "contas_seq", sequenceName = "softplan.contas_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(generator = "contas_seq", strategy = GenerationType.SEQUENCE)
	private Long id;

	private String numero;
	private double saldo;

	@Enumerated(EnumType.STRING)
	private Banco banco;

	public ContaBancaria() {
		super();
	}

	public ContaBancaria(Banco banco, String numero) {
		this();
		this.banco = banco;
		this.numero = numero;
	}

	public ContaBancaria(Banco banco, String numero, double saldoIncial) {
		this(banco, numero);
		this.saldo = saldoIncial;
	}

	// Metodos de negocio
	public void saque(double valor) {
		System.out.println("[ContaBancaria] saque de " + valor + " em conta " + this.numero + " e banco " + this.banco);
		if (valor <= 0)
			throw new IllegalArgumentException("Valor de saque inválido: " + valor);
		
		if(valor > this.saldo)
			throw new SaldoInsuficienteException("Saldo insuficiente. Conta " + this.numero + 
					" com saldo disponível de R$ " + this.saldo);
		
		this.saldo -= valor;
	}
	
	public void depositar(double valor) {
		System.out.println("[ContaBancaria] depósito de " + valor + " em conta " + this.numero + 
				" no banco " + this.banco);
		if (valor <= 0)
		throw new IllegalArgumentException("Valor de saque inválido: " + valor);
		
		this.saldo += valor;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public double getSaldo() {
		return saldo;
	}

	public void setSaldo(double saldo) {
		this.saldo = saldo;
	}

	public Banco getBanco() {
		return banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((numero == null) ? 0 : numero.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ContaBancaria other = (ContaBancaria) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (numero == null) {
			if (other.numero != null)
				return false;
		} else if (!numero.equals(other.numero))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ContaBancaria [id=" + id + ", numero=" + numero + ", saldo=" + saldo + ", banco=" + banco + "]";
	}

}

src/main/java/br/com/softplan/moduloIII/model/TransferenciaBancaria.java
package br.com.softplan.moduloIII.model;

import java.io.Serializable;

import javax.annotation.ManagedBean;
import javax.enterprise.context.Dependent;

/**
 * Classe que será utilizada como elemento de evento,
 * para quando ocorrer um transferência bancária.
 * @author JARDIER
 *
 */
@ManagedBean
@Dependent
public class TransferenciaBancaria implements Serializable {
	private static final long serialVersionUID = -7906722376167116567L;

	private String banco;
	private String contaOrigem;
	private String contaDestino;
	private double valor;

	public TransferenciaBancaria() {
		super();
	}
	
	public TransferenciaBancaria(String banco, String contaOrigem, String contaDestino, double valor) {
		this();
		this.banco = banco;
		this.contaOrigem = contaDestino;
		this.contaDestino = contaDestino;
		this.valor = valor;
	}

	public String getBanco() {
		return banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getContaOrigem() {
		return contaOrigem;
	}

	public void setContaOrigem(String contaOrigem) {
		this.contaOrigem = contaOrigem;
	}

	public String getContaDestino() {
		return contaDestino;
	}

	public void setContaDestino(String contaDestino) {
		this.contaDestino = contaDestino;
	}

	public double getValor() {
		return valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Override
	public String toString() {
		return "TransferenciaBancaria [banco=" + banco + ", contaOrigem=" + contaOrigem + ", contaDestino="
				+ contaDestino + ", valor=" + valor + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((banco == null) ? 0 : banco.hashCode());
		result = prime * result + ((contaOrigem == null) ? 0 : contaOrigem.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TransferenciaBancaria other = (TransferenciaBancaria) obj;
		if (banco == null) {
			if (other.banco != null)
				return false;
		} else if (!banco.equals(other.banco))
			return false;
		if (contaOrigem == null) {
			if (other.contaOrigem != null)
				return false;
		} else if (!contaOrigem.equals(other.contaOrigem))
			return false;
		return true;
	}

}

src/main/java/br/com/softplan/moduloIII/controller/CaixaMB.java
package br.com.softplan.moduloIII.controller;

import java.io.Serializable;

import javax.enterprise.event.Event;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.naming.InitialContext;

import br.com.softplan.moduloIII.enums.Banco;
import br.com.softplan.moduloIII.facede.ICaixaEletronico;
import br.com.softplan.moduloIII.interceptors.Logger;
import br.com.softplan.moduloIII.model.ContaBancaria;
import br.com.softplan.moduloIII.model.TransferenciaBancaria;
import br.com.softplan.moduloIII.qualifiers.BancoSoftplan;
import br.com.softplan.moduloIII.qualifiers.BancoSpocknet;
import br.com.softplan.moduloIII.stereotypes.Controller;
import br.com.softplan.moduloIV.ejb.GerenciadorEmailRemote;
import br.com.softplan.moduloIV.ejb.model.Email;

/*@Named
@RequestScoped*/
//Usaremos no Stereotype
@Controller
public class CaixaMB implements Serializable {
	private static final long serialVersionUID = 6909330016172148303L;

	// Utilizando o EJB Remote, interface. é recomendado nesse caso, a interface
	// Local, pois a aplicação, estão no mesmo container
	
	/*@EJB usaremos agora a injeção via contexto do CDI
	private GerenciadorEmailRemote gerenciadorEmail;*/
	
	@Inject
	private Email email;

	@Inject
	private TransferenciaBancaria transferenciaBancaria;

	@Inject
	@BancoSoftplan
	private ICaixaEletronico softplanCaixaEletronico;

	@Inject
	@BancoSpocknet
	private ICaixaEletronico spoknetCaixaEletronico;

	@Inject // gerenciador de Eventos
	@BancoSoftplan
	private Event<TransferenciaBancaria> gerenciadorEventos;

	private ContaBancaria conta = new ContaBancaria();

	public CaixaMB() {
		System.out.println("Criando instância de [CaixaMB]");

	}

	@Logger
	public void transferir() {
		System.out.println("[CaixaMB] executando transferência bancária.");
		
		try {
		//Injetando via contexto do JNDI
			InitialContext jndiContext = new InitialContext();
			String jndiName = "java:global/softplan/GerenciadorEmailBean!br.com.softplan.moduloIV.ejb.GerenciadorEmailRemote";
			
		GerenciadorEmailRemote	gerenciadorEmail = (GerenciadorEmailRemote) jndiContext.lookup(jndiName);
		//Enviando mensagem de email, usando EJB
		email.setDestinatario("jardier@hotmail.com");
		email.setAssunto("Transferência");
		email.setMensagem("Transferência da conta: " + transferenciaBancaria.getContaOrigem() +
				" no valor de R$ " + transferenciaBancaria.getValor() + " para a conta " + transferenciaBancaria.getContaDestino());
		
		gerenciadorEmail.enviarMensagem(email);
		

			if ("SOFTPLAN".equalsIgnoreCase(transferenciaBancaria.getBanco())) {

				softplanCaixaEletronico.transferir(transferenciaBancaria.getContaOrigem(),
						transferenciaBancaria.getContaDestino(), transferenciaBancaria.getValor());

				System.out.println("[CaixaMB] : Enviando evento de transferência " + transferenciaBancaria);
				gerenciadorEventos.fire(transferenciaBancaria);

			} else if ("SPOKNET".equalsIgnoreCase(transferenciaBancaria.getBanco())) {
				spoknetCaixaEletronico.transferir(transferenciaBancaria.getContaOrigem(),
						transferenciaBancaria.getContaDestino(), transferenciaBancaria.getValor());
			} else {
				throw new UnsupportedOperationException("Banco inválido.");
			}
			FacesContext ctx = FacesContext.getCurrentInstance();
			ctx.addMessage(null, new FacesMessage("Transferência realizada com sucesso."));

			transferenciaBancaria = new TransferenciaBancaria();

		} catch (Exception e) {
			FacesContext ctx = FacesContext.getCurrentInstance();
			ctx.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Erro ao tentar realizar uma transferência bancária. ", e.getMessage()));
		}
	}

	public void abrirConta() {
		System.out.println("[CaixaMB] Iniciando abertura de conta");
		try {
			if (Banco.SOFTPLAN.equals(conta.getBanco())) {
				System.out.println("Abrir conta no banco [SOFTPLAN]");
				softplanCaixaEletronico.abrirConta(conta);

			} else if (Banco.SPOKNET.equals(conta.getBanco())) {
				System.out.println("Abrir conta no banco [SPOKNET]");
				spoknetCaixaEletronico.abrirConta(conta);

			} else {
				throw new UnsupportedOperationException("Banco inválido.");
			}

			FacesContext ctx = FacesContext.getCurrentInstance();
			ctx.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Conta aberta com sucesso.",
					"[" + conta.getNumero() + "]"));

			conta = new ContaBancaria();

		} catch (Exception e) {
			FacesContext ctx = FacesContext.getCurrentInstance();
			ctx.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Erro ao tentar abrir a conta: [" + conta + "]", e.getMessage()));
		}
	}

	public ContaBancaria getConta() {
		return conta;
	}

	public void setConta(ContaBancaria conta) {
		this.conta = conta;
	}

	public Banco[] getBancos() {
		return Banco.values();
	}

	public TransferenciaBancaria getTransferenciaBancaria() {
		return transferenciaBancaria;

	}

	public void setTransferenciaBancaria(TransferenciaBancaria transferenciaBancaria) {
		this.transferenciaBancaria = transferenciaBancaria;
	}

}

src/main/java/br/com/softplan/moduloIII/stereotypes/Controller.java
package br.com.softplan.moduloIII.stereotypes;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import javax.annotation.ManagedBean;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Stereotype;
import javax.inject.Named;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Stereotype
@Target({ TYPE, METHOD, FIELD })
@Retention(RUNTIME)
@Documented
@ManagedBean
@Named
@RequestScoped
public @interface Controller {

}

src/main/webapp/moduloIII/banco/abrirConta.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:composition template="/moduloIV/templateRichafaces.xhtml">
	<ui:define name="titulo">
		<h:outputText value="Banco Softplan" />
	</ui:define>
	<ui:define name="subtitulo">
		<h:outputText value="Abertura de Conta" />
	</ui:define>

	<ui:define name="conteudo">
		<h:form id="formAbrirConta">
			<h:messages id="msg" />
			<h:panelGrid columns="2">

				<h:outputLabel value="Banco:" for="itBanco" />
				<h:selectOneMenu value="#{caixaMB.conta.banco}" id="itBanco"
					required="true"
					requiredMessage="O campo Banco deve ser selecionado">
					<f:selectItem itemLabel="Selecione..." itemValue=""
						noSelectionOption="false" />
					<f:selectItems value="#{caixaMB.bancos}" var="banco">
						<f:selectItem itemLabel="#{banco}" itemValue="#{banco}" />
					</f:selectItems>
					<f:ajax event="change" render="msg" />
				</h:selectOneMenu>

				<h:outputLabel value="Número da Conta: " for="itNumero" />
				<h:panelGroup>
					<h:inputText value="#{caixaMB.conta.numero}" id="itNumero"
						required="true" styleClass="iMask"
						requiredMessage="O número da Conta deve ser informado"
						alt="{type: 'fixed', mask: '99999-9', stripMask: false}">
					<f:ajax event="blur" render="msg" />
					</h:inputText>
					<h:outputText value="(99999-9)" />
				</h:panelGroup>

				<h:outputLabel value="Deposito Incial R$: " for="itSaldo" />
				<h:inputText value="#{caixaMB.conta.saldo}"
					id="itSaldo" styleClass="iMask"
					alt="{type:'number', groupSymbol:'.', groupDigits:3, decSymbol: ',', decDigits: 2, stripMask: false}">
					<f:convertNumber pattern="#,##0.00" locale="pt_BR" />
					<f:validateRequired />
					<f:ajax render="msg" />
				</h:inputText>

				<h:outputLabel value="" />
				<h:commandButton action="#{caixaMB.abrirConta()}"
					value="Abrir Conta" />

			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/moduloIII/banco/caixa.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:composition template="/moduloIV/templateRichafaces.xhtml">
	<ui:define name="titulo">
		<h:outputText value="Caixa Eletrônico" />
	</ui:define>
	<ui:define name="subtitulo">
		<h:outputText value="Caixa 130 Horas" />
	</ui:define>
	<ui:define name="conteudo">
		<h:form id="formTranferencia">
			<h:messages id="msg" showDetail="true" errorStyle="color: red;"
				infoStyle="color: yeelow" />
			<h:panelGrid columns="2">
			
				<h:outputLabel value="Banco:" for="itBanco" />
				<h:selectOneMenu value="#{caixaMB.transferenciaBancaria.banco}" id="itBanco">
					<f:selectItem itemLabel="Selecione..." itemValue="" noSelectionOption="false"/>
					<f:selectItems value="#{caixaMB.bancos}" var="banco">
						<f:selectItem itemLabel="#{banco}" itemValue="#{banco}"/>
					</f:selectItems>
				</h:selectOneMenu>
				
				<h:outputLabel value="Conta Origem:" for="itContaOrigem" />
				<h:inputText value="#{caixaMB.transferenciaBancaria.contaOrigem}" id="itContaOrigem"
					 required="true" requiredMessage="O campo Conta Origem é obrigatório">
						<f:ajax event="blur" render="msg"/>
				</h:inputText>
				
				<h:outputLabel value="Conta Destino" for="itContaDestino" />
				<h:inputText value="#{caixaMB.transferenciaBancaria.contaDestino}"  id="itContaDestino"
					required="true" requiredMessage="O campo Conta Destino é obrigatório">
					<f:ajax render="msg"/>	
				</h:inputText>
				
				<h:outputLabel value="Valor R$: " for="itValor" />
				<h:inputText value="#{caixaMB.transferenciaBancaria.valor}" id="itValor"
					styleClass="iMask"
					alt="{type:'number', groupSymbol:'.', groupDigits:3, decSymbol: ',', decDigits: 2, stripMask: false}">
					<f:convertNumber pattern="#,##0.00" locale="pt_BR"/>
					<f:validateRequired/>
					<f:ajax render="msg"/>
				</h:inputText>
				
				
				<h:commandButton action="#{caixaMB.transferir()}" value="Transferir" />
				<h:commandButton action="/moduloIII/banco/extrato" value="Extrato Online" immediate="true" />
				
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/moduloIII/banco/extrato.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:composition template="/moduloIV/templateRichafaces.xhtml">
	<ui:define name="titulo"><h:outputText value="Banco 130 Horas" /></ui:define>
	<ui:define name="subtitulo"><h:outputText value="Extrato Online Softplan" /> </ui:define>
	
	<ui:define name="conteudo">
		<h:form id="formExtratoOnline">
			<h:panelGrid columns="1" rendered="#{empty transferenciasSoftplan}">
				<h:outputLabel value="Nenhuma transferência foi realizada. Acesse o Caixa Eletrônico" />
				<h:commandButton action="/moduloIII/banco/caixa" value="Caixa Eletrônico" />
			</h:panelGrid>
			<h:dataTable value="#{transferenciasSoftplan}" var="transferencia" rendered="#{not empty transferenciasSoftplan}">
				<f:facet name="header">
					<h:outputText value="Transferência" />
				</f:facet>
				<f:facet name="footer">
					<h:commandButton action="/moduloIII/banco/caixa" value="Caixa Eletrônico" />
				</f:facet>
				
				<h:column>
					<f:facet name="header"><h:outputText value="Conta Origem" /></f:facet>
					<h:outputText value="#{transferencia.contaOrigem}" />
				</h:column>
				
				<h:column>
					<f:facet name="header"><h:outputText value="Conta Destino" /></f:facet>
					<h:outputText value="#{transferencia.contaDestino}" />
				</h:column>
				
				<h:column>
					<f:facet name="header"><h:outputText value="Valor R$" /></f:facet>
					<h:outputText value="#{transferencia.valor}">
						<f:convertNumber pattern="#,##0.00" locale="pt_BR"/>
					</h:outputText>
				</h:column>
			</h:dataTable>
		</h:form>
	</ui:define>
</ui:composition>
</html>